version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm run export
      - echo "Deploy Beginning"
      - aws s3 sync out/ "s3://${BUCKET_NAME}" --delete
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ] && [ "$BRANCH_NAME" == "master" ]; then
          echo "Creating S3 Redirect Objects on Master"
          touch gallery
          aws s3 cp gallery s3://heidihoelting.com --metadata '{"Website-Redirect-Location":"/gallery.html"}'
          touch about
          aws s3 cp about s3://heidihoelting.com --metadata '{"Website-Redirect-Location":"/about.html"}'
          touch contact
          aws s3 cp contact s3://heidihoelting.com --metadata '{"Website-Redirect-Location":"/contact.html"}'          
        fi
      - echo "Deploy Complete"
  post_build:
    commands:
      - echo "CodeBuild Status (0 == fail, 1 == success) - $CODEBUILD_BUILD_SUCCEEDING"
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          if [ $BRANCH_NAME == master ]; then
            aws cloudfront create-invalidation --distribution-id E3VXSWF40FW1P1 --paths /*
          fi
          echo "Build/Deploy success on branch ${BRANCH_NAME} on $(date)"
          aws sns publish --phone-number ${PHONE_NUMBER} --message "Build/deploy success. ${BUCKET_NAME}; ${BRANCH_NAME} branch; on $(date)"
        else
          echo "Build/Deploy failure"
        fi
