version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm run export
      - echo "Deploy Beginning"
      - aws s3 sync out/ "s3://${BUCKET_NAME}" --delete
      - echo "Deploy Complete"
  post_build:
    commands:
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - echo "Build/Deploy success on branch ${BRANCH_NAME} on $(date)"
      # - aws sns publish --phone-number ${PHONE_NUMBER} --message "Build/Deploy success on branch ${BRANCH_NAME} on $(date)"
