version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm run export
      - echo "Deploy Beginning"
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          if [ "$BRANCH_NAME" = "master" ]; then
            echo "Syncing files with AWS w/ Cache Control Headers"
            aws s3 sync out/ "s3://${BUCKET_NAME}" --exclude "*.html" --delete --cache-control max-age=31557600
            aws s3 sync out/ "s3://${BUCKET_NAME}" --exclude "*" --include "*.html" --cache-control max-age=0
            
            echo "Creating S3 Redirect Objects on Master"
            touch gallery
            aws s3api put-object --bucket heidihoelting.com --key gallery --website-redirect-location /gallery.html
            touch about
            aws s3api put-object --bucket heidihoelting.com --key about --website-redirect-location /about.html
            touch contact
            aws s3api put-object --bucket heidihoelting.com --key contact --website-redirect-location /contact.html    
          else
            echo "Syncing files with AWS"
            aws s3 sync out/ "s3://${BUCKET_NAME}" --delete
          fi
        else
          echo "Build/Deploy failure"
        fi
      - echo "Deploy Complete"
  post_build:
    commands:
      - echo "CodeBuild Status (0 == fail, 1 == success) - $CODEBUILD_BUILD_SUCCEEDING"
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          if [ "$BRANCH_NAME" = "master" ]; then
            echo Cloudfront ID - $CF_DIST_ID
            aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths /*
          fi
          echo "Build/Deploy success on branch ${BRANCH_NAME} on $(date)"
          aws sns publish --phone-number ${PHONE_NUMBER} --message "Build/deploy success. ${BUCKET_NAME}; ${BRANCH_NAME} branch; on $(date)"
        else
          echo "Build/Deploy failure"
        fi
